version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "04:30"
      timezone: "Asia/Shanghai"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "04:30"
      timezone: "Asia/Shanghai"
    commit-message:
      prefix: "chore"
      include: "scope"
